language: csharp
solution: Vz.AgentEngagement.sln

mono:
  - latest
  
install:
  - sudo apt-get install nunit-console
  - nuget restore Vz.AgentEngagement.sln
  
script:
  - xbuild Vz.AgentEngagement.sln
  - nunit-console Vz.AgentEngagement.Tests/bin/Debug/Vz.AgentEngagement.Tests.dll
