language: csharp
solution: Vz.AgentEngagement.sln
mono:
  - latest

deploy:
   edge: true
   provider: cloudfoundry
   username: hariraj@gmail.com
   password: Vishwak05
   api: https://api.run.pivotal.io
   organization: Hackathon
   space: development
